use super::support::*;
use super::*;

pub(crate) fn continuation_snapshot(continuation: &Continuation) -> Result<Value, String> {
    Ok(match continuation {
        Continuation::ContinueBlock {
            block,
            next_stmt_index,
            frame,
        } => json!({
            "kind": "continue_block",
            "block": block.0,
            "next_stmt_index": next_stmt_index,
            "frame": frame_snapshot(frame),
        }),
        Continuation::Bind {
            block,
            next_stmt_index,
            pat,
            span,
            frame,
        } => json!({
            "kind": "bind",
            "block": block.0,
            "next_stmt_index": next_stmt_index,
            "pat": pat.0,
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::Assign {
            block,
            next_stmt_index,
            target,
            span,
            frame,
        } => json!({
            "kind": "assign",
            "block": block.0,
            "next_stmt_index": next_stmt_index,
            "target": target.0,
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::AssignTargetIndex {
            block,
            next_stmt_index,
            root_symbol,
            segments,
            components,
            next_component_index,
            new_value,
            span,
            frame,
        } => json!({
            "kind": "assign_target_index",
            "block": block.0,
            "next_stmt_index": next_stmt_index,
            "root_symbol": root_symbol.0,
            "segments": segments.iter().map(local_place_segment_snapshot).collect::<Vec<_>>(),
            "components": components.iter().map(local_place_component_snapshot).collect::<Vec<_>>(),
            "next_component_index": next_component_index,
            "new_value": value_json(new_value),
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::FieldReceiver {
            expr,
            field,
            span,
            frame,
        } => json!({
            "kind": "field_receiver",
            "expr": expr.0,
            "field": field,
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::Unary { op, span } => json!({
            "kind": "unary",
            "op": unary_op_name(*op),
            "span": span_snapshot(*span),
        }),
        Continuation::BinaryLeft {
            op,
            rhs,
            span,
            frame,
        } => json!({
            "kind": "binary_left",
            "op": binary_op_name(*op),
            "rhs": rhs.0,
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::BinaryRight { op, left, span } => json!({
            "kind": "binary_right",
            "op": binary_op_name(*op),
            "left": value_json(left),
            "span": span_snapshot(*span),
        }),
        Continuation::AggregateElement {
            kind,
            exprs,
            next_index,
            values,
            frame,
        } => json!({
            "kind": "aggregate_element",
            "aggregate_kind": aggregate_kind_name(*kind),
            "exprs": exprs.iter().map(|expr| expr.0).collect::<Vec<_>>(),
            "next_index": next_index,
            "values": values.iter().map(value_json).collect::<Vec<_>>(),
            "frame": frame_snapshot(frame),
        }),
        Continuation::ListConsHead { tail, span, frame } => json!({
            "kind": "list_cons_head",
            "tail": tail.0,
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::ListConsTail { head, span } => json!({
            "kind": "list_cons_tail",
            "head": value_json(head),
            "span": span_snapshot(*span),
        }),
        Continuation::RangeStart { end, bounds, frame } => json!({
            "kind": "range_start",
            "end": end.0,
            "bounds": range_bounds_name(*bounds),
            "frame": frame_snapshot(frame),
        }),
        Continuation::RangeEnd { start, bounds } => json!({
            "kind": "range_end",
            "start": value_json(start),
            "bounds": range_bounds_name(*bounds),
        }),
        Continuation::RecordField {
            nominal_type,
            fields,
            next_index,
            values,
            frame,
        } => json!({
            "kind": "record_field",
            "nominal_type": nominal_type.map(|ty| ty.0),
            "fields": fields.iter().map(field_init_snapshot).collect::<Result<Vec<_>, _>>()?,
            "next_index": next_index,
            "values": values.iter().map(|(name, value)| json!({
                "name": name,
                "value": value_json(value),
            })).collect::<Vec<_>>(),
            "frame": frame_snapshot(frame),
        }),
        Continuation::MapKey {
            entries,
            index,
            values,
            frame,
        } => json!({
            "kind": "map_key",
            "entries": entries.iter().map(map_entry_snapshot).collect::<Vec<_>>(),
            "index": index,
            "values": map_values_snapshot(values),
            "frame": frame_snapshot(frame),
        }),
        Continuation::MapValue {
            entries,
            index,
            key,
            values,
            frame,
        } => json!({
            "kind": "map_value",
            "entries": entries.iter().map(map_entry_snapshot).collect::<Vec<_>>(),
            "index": index,
            "key": value_json(key),
            "values": map_values_snapshot(values),
            "frame": frame_snapshot(frame),
        }),
        Continuation::IndexBase {
            expr,
            index,
            span,
            frame,
        } => json!({
            "kind": "index_base",
            "expr": expr.0,
            "index": index.0,
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::IndexValue { expr, base, span } => json!({
            "kind": "index_value",
            "expr": expr.0,
            "base": value_json(base),
            "span": span_snapshot(*span),
        }),
        Continuation::SliceBase { eval, frame } => json!({
            "kind": "slice_base",
            "eval": slice_eval_snapshot(eval),
            "frame": frame_snapshot(frame),
        }),
        Continuation::SliceStart { eval, base, frame } => json!({
            "kind": "slice_start",
            "eval": slice_eval_snapshot(eval),
            "base": value_json(base),
            "frame": frame_snapshot(frame),
        }),
        Continuation::SliceEnd { eval, base, start } => json!({
            "kind": "slice_end",
            "eval": slice_eval_snapshot(eval),
            "base": value_json(base),
            "start": value_json(start),
        }),
        Continuation::MethodReceiver {
            expr,
            method,
            type_args,
            args,
            span,
            frame,
        } => json!({
            "kind": "method_receiver",
            "expr": expr.0,
            "method": method,
            "type_args": type_args.iter().map(|ty| ty.0).collect::<Vec<_>>(),
            "args": args.iter().map(arg_snapshot).collect::<Vec<_>>(),
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::PromptValueMethodArg {
            messages,
            method,
            role,
            allow_plain_system_content,
            span,
        } => json!({
            "kind": "prompt_value_method_arg",
            "messages": messages.iter().map(prompt_message_snapshot).collect::<Vec<_>>(),
            "method": method,
            "role": prompt_role_name(*role),
            "allow_plain_system_content": allow_plain_system_content,
            "span": span_snapshot(*span),
        }),
        Continuation::LocalMethodArgs {
            expr,
            receiver,
            method,
            type_args,
            args,
            next_arg_index,
            evaluated_args,
            span,
            frame,
        } => json!({
            "kind": "local_method_args",
            "expr": expr.0,
            "receiver": value_json(receiver),
            "method": method,
            "type_args": type_args.iter().map(|ty| ty.0).collect::<Vec<_>>(),
            "args": args.iter().map(arg_snapshot).collect::<Vec<_>>(),
            "next_arg_index": next_arg_index,
            "evaluated_args": evaluated_args.iter().map(value_json).collect::<Vec<_>>(),
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::StaticMethodArgs {
            expr,
            kind,
            method,
            type_args,
            args,
            next_arg_index,
            evaluated_args,
            span,
            frame,
        } => json!({
            "kind": "static_method_args",
            "expr": expr.0,
            "static_kind": static_method_kind_snapshot(kind),
            "method": method,
            "type_args": type_args.iter().map(|ty| ty.0).collect::<Vec<_>>(),
            "args": args.iter().map(arg_snapshot).collect::<Vec<_>>(),
            "next_arg_index": next_arg_index,
            "evaluated_args": evaluated_args.iter().map(value_json).collect::<Vec<_>>(),
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::SpecMethodReceiver {
            expr,
            receiver_expr,
            spec_symbol,
            spec_args,
            method,
            args,
            span,
            frame,
        } => json!({
            "kind": "spec_method_receiver",
            "expr": expr.0,
            "receiver_expr": receiver_expr.0,
            "spec_symbol": spec_symbol.0,
            "spec_args": spec_args.iter().map(|ty| ty.0).collect::<Vec<_>>(),
            "method": method,
            "args": args.iter().map(arg_snapshot).collect::<Vec<_>>(),
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::CalleeEval { args, span, frame } => json!({
            "kind": "callee_eval",
            "args": args.iter().map(arg_snapshot).collect::<Vec<_>>(),
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::PipelineStageTarget {
            stages,
            next_stage_index,
            targets,
            current_limits,
            span,
            frame,
        } => json!({
            "kind": "pipeline_stage_target",
            "stages": stages.iter().map(stage_snapshot).collect::<Vec<_>>(),
            "next_stage_index": next_stage_index,
            "targets": targets.iter().map(call_target_snapshot).collect::<Vec<_>>(),
            "current_limits": current_limits.iter().map(runtime_limit_snapshot).collect::<Vec<_>>(),
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::CallArgs {
            target,
            args,
            next_arg_index,
            evaluated_args,
            span,
            frame,
        } => json!({
            "kind": "call_args",
            "target": call_target_snapshot(target),
            "args": args.iter().map(arg_snapshot).collect::<Vec<_>>(),
            "next_arg_index": next_arg_index,
            "evaluated_args": evaluated_args.iter().map(value_json).collect::<Vec<_>>(),
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::VariantArgs {
            variant_symbol,
            args,
            next_arg_index,
            evaluated_args,
            span,
            frame,
        } => json!({
            "kind": "variant_args",
            "variant_symbol": variant_symbol.0,
            "args": args.iter().map(arg_snapshot).collect::<Vec<_>>(),
            "next_arg_index": next_arg_index,
            "evaluated_args": evaluated_args.iter().map(value_json).collect::<Vec<_>>(),
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::PerformArgs {
            expr,
            type_args,
            next_arg_index,
            evaluated_args,
            frame,
            ..
        } => json!({
            "kind": "perform_args",
            "expr": expr.0,
            "type_args": type_args.iter().map(|ty| ty.0).collect::<Vec<_>>(),
            "next_arg_index": next_arg_index,
            "evaluated_args": evaluated_args.iter().map(value_json).collect::<Vec<_>>(),
            "frame": frame_snapshot(frame),
        }),
        Continuation::MemoryArgs {
            region_stable_id,
            path,
            key_type,
            value_type,

            result_type,
            method,
            args,
            next_arg_index,
            evaluated_args,
            span,
            frame,
        } => json!({
            "kind": "memory_args",
            "result_type": result_type.0,
            "region_stable_id": region_stable_id,
            "path": path,
            "key_type": key_type.0,
            "value_type": value_type.0,
            "method": method,
            "args": args.iter().map(arg_snapshot).collect::<Vec<_>>(),
            "next_arg_index": next_arg_index,
            "evaluated_args": evaluated_args.iter().map(value_json).collect::<Vec<_>>(),
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::MemorySelectionLimitArgs {
            region_stable_id,
            path,
            key_type,
            value_type,
            kind,
            predicate,
            limit,
            args,
            next_arg_index,
            evaluated_args,
            span,
            frame,
        } => json!({
            "kind": "memory_selection_limit_args",
            "region_stable_id": region_stable_id,
            "path": path,
            "key_type": key_type.0,
            "value_type": value_type.0,
            "selection_kind": crate::value::codec::memory_selection_kind_json(kind),
            "predicate": predicate.as_ref().map(value_json),
            "limit": limit,
            "args": args.iter().map(arg_snapshot).collect::<Vec<_>>(),
            "next_arg_index": next_arg_index,
            "evaluated_args": evaluated_args.iter().map(value_json).collect::<Vec<_>>(),
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::IfExpr {
            then_block,
            else_branch,
            span,
            frame,
        } => json!({
            "kind": "if_expr",
            "then_block": then_block.0,
            "else_branch": else_branch.as_ref().map(else_branch_snapshot),
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::IfStmt {
            block,
            next_stmt_index,
            then_block,
            else_branch,
            span,
            frame,
        } => json!({
            "kind": "if_stmt",
            "block": block.0,
            "next_stmt_index": next_stmt_index,
            "then_block": then_block.0,
            "else_branch": else_branch.as_ref().map(else_branch_snapshot),
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::MatchExpr { arms, span, frame } => json!({
            "kind": "match_expr",
            "arms": arms.iter().map(match_arm_snapshot).collect::<Vec<_>>(),
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::MatchStmt {
            block,
            next_stmt_index,
            arms,
            span,
            frame,
        } => json!({
            "kind": "match_stmt",
            "block": block.0,
            "next_stmt_index": next_stmt_index,
            "arms": arms.iter().map(match_arm_snapshot).collect::<Vec<_>>(),
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::HandleHandler {
            handle_expr,
            body,
            handler,
            span,
            frame,
        } => json!({
            "kind": "handle_handler",
            "handle_expr": handle_expr.0,
            "body": body.0,
            "handler": handler.0,
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::PipelineInput {
            stages,
            span,
            frame,
        } => json!({
            "kind": "pipeline_input",
            "stages": stages.iter().map(stage_snapshot).collect::<Vec<_>>(),
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::PipelineTarget { input, span } => json!({
            "kind": "pipeline_target",
            "input": value_json(input),
            "span": span_snapshot(*span),
        }),
        Continuation::ComposedCall { remaining, span } => json!({
            "kind": "composed_call",
            "remaining": remaining.iter().map(call_target_snapshot).collect::<Vec<_>>(),
            "span": span_snapshot(*span),
        }),
        Continuation::RestoreModelPolicy { previous, inner } => json!({
            "kind": "restore_model_policy",
            "previous": model_policy_snapshot(previous),
            "inner": continuation_snapshot(inner)?,
        }),
        Continuation::TryExpr { expr, span } => json!({
            "kind": "try_expr",
            "expr": expr.0,
            "span": span_snapshot(*span),
        }),
        Continuation::MemoryClearDeleteAll {
            region_stable_id,
            path,
            span,
        } => json!({
            "kind": "memory_clear_delete_all",
            "region_stable_id": region_stable_id,
            "path": path,
            "span": span_snapshot(*span),
        }),
        Continuation::MemoryClearDeleteNext {
            region_stable_id,
            path,
            remaining_keys,
            next_index,
            span,
        } => json!({
            "kind": "memory_clear_delete_next",
            "region_stable_id": region_stable_id,
            "path": path,
            "remaining_keys": remaining_keys.iter().map(value_json).collect::<Vec<_>>(),
            "next_index": next_index,
            "span": span_snapshot(*span),
        }),
        Continuation::ForLoop {
            pat,
            values,
            next_index,
            body,
            iterations,
            loop_scope,
            span,
            frame,
        } => {
            let mut scope = loop_scope.iter().map(|symbol| symbol.0).collect::<Vec<_>>();
            scope.sort_unstable();
            json!({
                "kind": "for_loop",
                "pat": pat.0,
                "values": values.as_ref().map(|values| values.iter().map(value_json).collect::<Vec<_>>()),
                "next_index": next_index,
                "body": body.0,
                "iterations": iterations,
                "loop_scope": scope,
                "span": span_snapshot(*span),
                "frame": frame_snapshot(frame),
            })
        }
        Continuation::WhileLoop {
            cond,
            body,
            iteration,
            max_iterations,
            resume_after_body,
            span,
            frame,
        } => json!({
            "kind": "while_loop",
            "cond": cond.0,
            "body": body.0,
            "iteration": iteration,
            "max_iterations": max_iterations,
            "resume_after_body": resume_after_body,
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::RetryAttempt {
            retry,
            body,
            attempts,
            next_attempt,
            block,
            next_stmt_index,
            frame,
        } => json!({
            "kind": "retry_attempt",
            "retry_id": retry.id.0,
            "retry_ordinal": retry.ordinal,
            "body": body.0,
            "attempts": attempts,
            "next_attempt": next_attempt,
            "block": block.0,
            "next_stmt_index": next_stmt_index,
            "frame": frame_snapshot(frame),
        }),
        Continuation::HandleBoundary {
            scope_id,
            inner,
            handlers,
            span,
            frame,
        } => json!({
            "kind": "handle_boundary",
            "scope_id": scope_id.0,
            "inner": continuation_snapshot(inner)?,
            "handlers": handlers.iter().map(handler_arm_snapshot).collect::<Vec<_>>(),
            "span": span_snapshot(*span),
            "frame": frame_snapshot(frame),
        }),
        Continuation::HandlerDispatch { outer } => json!({
            "kind": "handler_dispatch",
            "outer": continuation_snapshot(outer)?,
        }),
        Continuation::AgentPromptBody {
            item,
            span,
            model_policy,
        } => json!({
            "kind": "agent_prompt_body",
            "item": item.0,
            "span": span_snapshot(*span),
            "model_policy": model_policy.as_ref().map(|policy| model_policy_snapshot(policy)),
        }),
        Continuation::ScopedModelPolicy { policy, inner } => json!({
            "kind": "scoped_model_policy",
            "policy": model_policy_snapshot(policy),
            "inner": continuation_snapshot(inner)?,
        }),
        Continuation::CallBoundary { outer } => json!({
            "kind": "call_boundary",
            "outer": continuation_snapshot(outer)?,
        }),
        Continuation::Chain { inner, outer } => json!({
            "kind": "chain",
            "inner": continuation_snapshot(inner)?,
            "outer": continuation_snapshot(outer)?,
        }),
        Continuation::Return => json!({ "kind": "return" }),
        Continuation::Resume => json!({ "kind": "resume" }),
        Continuation::Finish => json!({ "kind": "finish" }),
        Continuation::BlockValue => json!({ "kind": "block_value" }),
    })
}
